apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tls-approver
  namespace: kube-system
  labels:
    k8s-app: tls-approver
spec:
  replicas: 1
  template:
    metadata:
      name: tls-approver
      labels:
        k8s-app: tls-approver
    spec:
      containers:
      - name: tls-approver
        imagePullPolicy: IfNotPresent
        image: repo.lab.ppops.net/dev-docker-local/kapprover:latest
        args:
          - -filter=group=system:serviceaccounts
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
